### ISSUE TITLE
Include iFrames in Report

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/csis-helpers-module#13]
We need iFrame support in [csis_include_in_report.js](https://github.com/clarity-h2020/csis-helpers-module/blob/dev/js/csis_include_in_report.js). 

Not sure if that's going to work. We can try it with the [MCDA App](https://csis.myclimateservice.eu/study/1/step/22/view/scenario-analysis) (which is currently [broken](https://github.com/clarity-h2020/scenario-analysis/issues/15)) until iFrame Support for the [Map Component](https://github.com/clarity-h2020/map-component/issues/37) is available.

**Comment by p-a-s-c-a-l** [comment]
Include in report button for iFrames is implemented and can be tested e.g. [here](https://csis.myclimateservice.eu/study/1/step/22/view/scenario-analysis). However, unfortunately html2canvas creates a [blank snapshot](https://csis.myclimateservice.eu/sites/default/files/report-images/2019-08/map-snapshot_4.png) of the iframe. 

So instead of the iFrame as a whole, we maybe have to select an element within the iFrame as described [here](https://stackoverflow.com/a/24578653).

**Comment by p-a-s-c-a-l** [comment]
Tried with [this study](https://csis.myclimateservice.eu/study/25/view/data), but got:

`error posting report image`

It would be helpful to log the concrete error in [csis_include_in_report.js#L168](https://github.com/clarity-h2020/csis-helpers-module/blob/dev/js/csis_include_in_report.js#L168)

**Comment by patrickkaleta** [comment]
True, I was expecting the [Drupal logger](https://csis.myclimateservice.eu/admin/reports/dblog) to log such errors, but he doesn't. I will log the error messages directly in the script. 

The image file itself is created, but it fails when creating the Report Image entity, so I'm guessing that's because there is no GL-step available on [that page](https://csis.myclimateservice.eu/study/25/view/data) to which the Report Image could be linked.

I need to add it directly to the Study group, but I remember there were some [issues](https://www.drupal.org/project/group/issues/2872645) with JSON:API altering Group instances. Was couple of months ago, might have been solved by now. I will look into this.

**Comment by therter** [comment]
> I'm guessing that's because there is no GL-step available on [that page](https://csis.myclimateservice.eu/study/25/view/data) to which the Report Image could be linked.

Yes, this should be the problem now. 
First, the request to create the Report Image Entity answered with a  ```413 Request Entity too large```, but since this is solved, the request answers with a ```404 The resource identified by 'node--gl_step:-1' (given as a relationship item) could not be found```

**Comment by p-a-s-c-a-l** [comment]
Status @therter ?
What's going on in this branch:  [bug/9_use_table_div](https://github.com/clarity-h2020/csis-helpers-module/tree/bug/9_use_table_div)?

Answer is [here](https://github.com/clarity-h2020/csis-helpers-module/issues/9#issuecomment-534938948)

**Comment by p-a-s-c-a-l** [comment]
Is there a possibility to increase the resolution of the snapshot? This [snapshot image](https://csis.myclimateservice.eu/sites/default/files/styles/max_650x650/public/report-images/2019-09/map-snapshot_70.png) is even smaller than the original map shown on the screen. For printing, this is not suitable.

Please note the URI of the image: /sites/default/files/**styles/max_650x650/**. So for some reason the size is limited to max. 650x650px when uploading (?) the image. Is this a restriction at Drupal side or at html2canvas side?

**Comment by patrickkaleta** [comment]
> Is there a possibility to increase the resolution of the snapshot? This [snapshot image](https://csis.myclimateservice.eu/sites/default/files/styles/max_650x650/public/report-images/2019-09/map-snapshot_70.png) is even smaller than the original map shown on the screen. For printing, this is not suitable.
> 
> Please note the URI of the image: /sites/default/files/**styles/max_650x650/**. So for some reason the size is limited to max. 650x650px when uploading (?) the image. Is this a restriction at Drupal side or at html2canvas side?

No, this is not a Drupal or html2canvas restriction, that's just how drupal handles images. The original image taken by html2canvas is [this](https://csis.myclimateservice.eu/sites/default/files/report-images/2019-09/map-snapshot_70.png) one (your previous URI without the "/styles/max_650x650/public"). 

Drupal allows to define different [image styles](https://csis.myclimateservice.eu/admin/config/media/image-styles), which you can then use in either Views or display modes. That will determine how the image will be shown in the FE.
![image-styles](https://user-images.githubusercontent.com/42167036/65672509-7f085e00-e049-11e9-95e3-c1797c4cb69f.png)

AFAIK we use the default style (so the original image resolution) on all report images. Since you managed to find one in a 650x650 resolution, I guess we have a misconfiguration somewhere. 

@p-a-s-c-a-l  Where exactly did you find this image being displayed?

**Comment by therter** [comment]
> So for some reason the size is limited to max. 650x650px when uploading (?) the image. Is this a restriction at Drupal side or at html2canvas side?

On html2canvas side, it is possible to increase the resolution of the image with the scale option. But drupal does not accept such images, because they are too large.

In my local instance, I get the following error message:

`Symfony\Component\HttpKernel\Exception\UnprocessableEntityHttpException: Unprocessable Entity: file validation failed. The file is 2.39 MB exceeding the maximum file size of 2 MB. in Drupal\jsonapi\Controller\FileUpload->handleFileUploadForNewResource() (line 177 of /app/web/core/modules/jsonapi/src/Controller/FileUpload.php).`

I will try to increase the allowed file size locally to test images with a higher resolution.

**Comment by patrickkaleta** [comment]
> > So for some reason the size is limited to max. 650x650px when uploading (?) the image. Is this a restriction at Drupal side or at html2canvas side?
> 
> On html2canvas side, it is possible to increase the resolution of the image with the scale option. But drupal does not accept such images, because they are too large.

Oh interesting, I didn't know that. But where is this currently applied? I just took a screenshot of the Study Area for [Study 30](https://csis.myclimateservice.eu/study/30/view/area) and one screenshot of the [hazard map](https://csis.myclimateservice.eu/study/30/step/1403/view/maps). In both cases ([image 1](https://csis.myclimateservice.eu/sites/default/files/report-images/2019-09/map-snapshot_72.png), [image 2](https://csis.myclimateservice.eu/sites/default/files/report-images/2019-09/map-snapshot_74.png)) html2canvas created the images with the same resolution as shown on the website.

**Comment by therter** [comment]
> But where is this currently applied?

Since the drupal system currently does not accept large images, this isn't applied, yet.

**Comment by p-a-s-c-a-l** [comment]
> Where exactly did you find this image being displayed?

Right after clicking the include in report button and on **preview**. So the 650x650 resolution is probably o.k,. for preview mode and we don't have to change it as long as the full resolution is available in the (PDF) report.

**Comment by patrickkaleta** [comment]
> > But where is this currently applied?
> 
> Since the drupal system currently does not accept large images, this isn't applied, yet.

Oh my mistake, I though you said that html2canvas is currently limiting the resolution to 650x650.

**Comment by patrickkaleta** [comment]
> > Where exactly did you find this image being displayed?
> 
> Right after clicking the include in report button and on **preview**. So the 650x650 resolution is probably o.k,. for preview mode and we don't have to change it as long as the full resolution is available in the (PDF) report.

Ah right. Denis just recently included the image in the [edit form](https://csis.myclimateservice.eu/admin/structure/types/manage/report_image/form-display) of the report image and set the formatter style to 650x650. However, that does not impact how the image is later shown in the PDF, so we don't need to fix that.

**Comment by therter** [comment]
To allow the upload of bigger images, the file /usr/local/etc/php/conf.d/uploads.ini has to be created. The content of the file should be something like this:

```
file_uploads = On
memory_limit = 64M
upload_max_filesize = 64M
post_max_size = 64M
max_execution_time = 600
```

**Comment by p-a-s-c-a-l** [comment]
> To allow the upload of bigger images, the file /usr/local/etc/php/conf.d/uploads.ini has to be created.

@therter What's the status? How is this solved within our drupal docker container?

**Comment by therter** [comment]
I have added the file upload.ini to the docker-compose.yml. The attempts with the  configuration in the folder /app/web/sites/default did not work

**Comment by p-a-s-c-a-l** [comment]
Implemented. But there is still a [bug](https://github.com/clarity-h2020/csis-helpers-module/issues/9).
