### ISSUE TITLE
Support for additional processing variables

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/csis-helpers-module#14]
ATM just the processing variable `$emikat_id` for advanced/automated/calculated screening studies is supported in [csis_helpers.module](https://github.com/clarity-h2020/csis-helpers-module/blob/dev/csis_helpers.module). The respective query parameter is set by [csis_iframe_connector.js](https://github.com/clarity-h2020/csis-helpers-module/blob/dev/js/csis_iframe_connector.js) as part of the iFrame URL and then processed by [BasicMap.js](https://github.com/clarity-h2020/map-component/blob/dev/src/components/commons/BasicMap.js).

Additional parameters have to be supported, see https://github.com/clarity-h2020/data-package/issues/42#issuecomment-527425289 and https://github.com/clarity-h2020/map-component/issues/54 for more details.

**Comment by p-a-s-c-a-l** [comment]
Once https://github.com/clarity-h2020/csis/issues/101 has been implemented, we need to include `study_variant, time_period, emission_scenario and event_frequency`in the `csisHelpers.studyInfo` JS Object.

**Comment by p-a-s-c-a-l** [comment]
Not sure if this changed lately, but the study_presets contain wrong values: e.g. instead of "scenario:historial" EMIKAT expects "Baseline" as value for emissions_scenario:

![grafik](https://user-images.githubusercontent.com/1788226/65743685-f72c5d80-e0f5-11e9-9531-36d73f23a304.png)

[Here](https://github.com/clarity-h2020/data-package/issues/42#issuecomment-531742464) is documented what is expected by the table and map applications.

**Comment by p-a-s-c-a-l** [comment]
O.K., I tried to revolve this in branch [feature/010-extend-entityinfo](https://github.com/clarity-h2020/csis-helpers-module/tree/feature/010-extend-entityinfo) by accessing `field_var_value`instead of `field_var_meaning`, but this didn't work:

```The website encountered an unexpected error. Please try again later.</br></br><em class="placeholder">InvalidArgumentException</em>: Field field_var_value is unknown. in <em class="placeholder">Drupal\Core\Entity\ContentEntityBase-&gt;getTranslatedField()</em> (line <em class="placeholder">587</em> of <em class="placeholder">core/lib/Drupal/Core/Entity/ContentEntityBase.php</em>).```

**Comment by p-a-s-c-a-l** [comment]
Another thing we need in 'study_info' is 'field_eea_city_profile_name' from the [Cities/Regions Taxonomy](https://csis.myclimateservice.eu/admin/structure/taxonomy/manage/cities_regions/overview/fields). Maybe @patrickkaleta can add this, too?

**Comment by DenoBeno** [comment]
Do you mean the "scenario:historical" and such?

If yes, this is a very simple thing to fix. Or at least to work around until we do something better. Let me explain:

We have *two* taxonomies governing the issue at hand: "DP variable meanings" and "DP variables"

![grafik](https://user-images.githubusercontent.com/2961790/65750971-de2da780-e109-11e9-848d-f2816866ca27.png)

DP variables is used in the ressource tags, whereas the DP variables meanings is used in study to indicate which combinations the user wants. Why two and not one? Because EMIKAT uses the "Baseline" where our hazard packages use the "historical" and we need some way to map this to one other.

Thus, the workaround is simply to replace the value of "meaning ID" variable in DP variables meanings taxonomy so that it's the same as the "variable value" in DP variables. I'll do this now and then your applications will get what they need.

**TODO later**
One day when we start doing this for non-emikat resources, we'll have to deal with the issue of synonyms. In one way or another, the helpers modules wil lhave to signal that emission scenario can be either "Baseline" or "historical" and the apps will ahve to parse the resource tags to find out which of the two these resources can understand. The alternative woudl be to hard-code such knowledge somewhere - I don't like that idea.

Resolving this is a pre-requisite for https://github.com/clarity-h2020/data-package/issues/47

**Comment by DenoBeno** [comment]
OK, I have finished setting the "meaning ID" values. If there is any error left, you can fix it here: https://csis.myclimateservice.eu/admin/structure/taxonomy/manage/dp_variable_meanings/overview

This said, the titles of the "dp variable meaning" taxonomy terms are meant to be used as labels on CSIS UI. So they should probably also be exposed by csis helpers.

**Comment by patrickkaleta** [comment]
> O.K., I tried to revolve this in branch [feature/010-extend-entityinfo](https://github.com/clarity-h2020/csis-helpers-module/tree/feature/010-extend-entityinfo) by accessing `field_var_value`instead of `field_var_meaning`, but this didn't work:
> 
> `The website encountered an unexpected error. Please try again later.</br></br><em class="placeholder">InvalidArgumentException</em>: Field field_var_value is unknown. in <em class="placeholder">Drupal\Core\Entity\ContentEntityBase-&gt;getTranslatedField()</em> (line <em class="placeholder">587</em> of <em class="placeholder">core/lib/Drupal/Core/Entity/ContentEntityBase.php</em>).`

@p-a-s-c-a-l 
As explained by Denis, there are two taxonomies at play here and you were trying to access the field of one taxonomy in the second taxonomy, where it's not present... and Drupal doesn't like things like that. 

Denis already finished his workaround, so you should now get the wished results. I will revert the changes in [feature/010-extend-entityinfo](https://github.com/clarity-h2020/csis-helpers-module/tree/feature/010-extend-entityinfo).

> Another thing we need in 'study_info' is 'field_eea_city_profile_name' from the Cities/Regions Taxonomy. Maybe @patrickkaleta can add this, too?

That field was added to the **studyInfo** object already a while ago. It's called `eea_city_name`, but I can rename it to `eea_city_profile_name` if you like.
![studyInfo-attributes](https://user-images.githubusercontent.com/42167036/65752741-b17b8f00-e10d-11e9-8dab-214b17aafa17.png)

**Comment by p-a-s-c-a-l** [comment]
> but I can rename it to `eea_city_profile_name` if you like.

no it's o.k. Thanks.

regarding the variables / taxonomies / taxonomy mappings / meanings / .... : we shouldn't overcomplicate things. lets keep it simple and move on.

**Comment by DenoBeno** [comment]
I wonder what is the status of this ticket now?

In principle we have all we need at the moment. So maybe it's done?
We also know that more will be needed later, see https://github.com/clarity-h2020/csis-helpers-module/issues/14#issuecomment-535830997. So is it on hold then?

**Comment by p-a-s-c-a-l** [comment]
It's done. We open a new issue if we need more.
